# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("recurring needs only one approval",
     "needed = APPROVALS_RECURRING if outcome == RECURRING else APPROVALS_ONE_OFF",
     "needed = APPROVALS_ONE_OFF"),
    ("one-off keeps the declared periods",
     "        if record.outcome == RECURRING:\n            return int(record.periods_asked)\n        return 1",
     "        return int(record.periods_asked)"),
    ("recurring schedule collapses to one period",
     "        if record.outcome == RECURRING:\n            return int(record.periods_asked)\n",
     "        if record.outcome == RECURRING:\n            return 1\n"),
    ("approval threshold off by one",
     "        if count >= int(record.needed):", "        if count > int(record.needed):"),
    ("period length ignored (a period every day)",
     "if today < int(record.approved_day) + PERIOD_DAYS * k:", "if today < int(record.approved_day) + k:"),
    ("due check off by one (due day itself refused)",
     "if today < int(record.approved_day) + PERIOD_DAYS * k:",
     "if today <= int(record.approved_day) + PERIOD_DAYS * k:"),
    ("approval day not recorded",
     "            record.approved_day = u256(self._today())", "            record.approved_day = u256(0)"),
    ("fail-safe flipped on unparseable output",
     "                    return {\"outcome\": ONE_OFF}\n            if not isinstance(data, dict):",
     "                    return {\"outcome\": RECURRING}\n            if not isinstance(data, dict):"),
    ("unknown label maps to RECURRING",
     "            if outcome == RECURRING:\n                return {\"outcome\": RECURRING}\n            return {\"outcome\": ONE_OFF}",
     "            if outcome == ONE_OFF:\n                return {\"outcome\": ONE_OFF}\n            return {\"outcome\": RECURRING}"),
    ("validator accepts any valid label",
     "                return str(mine.get(\"outcome\", \"\")).strip().upper() == leader_outcome",
     "                return True"),
    ("anyone may approve",
     "        if (record.ledger_id + \"|\" + caller) not in self.approvers:", "        if False:"),
    ("requester may approve own request",
     "        if caller == record.requester:", "        if False:"),
    ("the same approver counts twice",
     "        if key in self.approved_by:", "        if False:"),
    ("anyone may mark payments",
     "        if caller != self.ledgers[record.ledger_id].owner:\n            raise gl.vm.UserError(\"Only the ledger owner may mark payments\")",
     "        if caller == \"\":\n            raise gl.vm.UserError(\"Only the ledger owner may mark payments\")"),
    ("a period may be paid twice",
     "        if key in self.paid:", "        if False:"),
    ("paying every period does not complete",
     "            record.state = R_COMPLETED\n", "            record.state = R_APPROVED\n"),
    ("anyone may cancel",
     "        if caller != record.requester and caller != self.ledgers[record.ledger_id].owner:",
     "        if caller == \"\":"),
    ("cancelled request still counts as committed",
     "        if record.state != R_APPROVED:\n            return 0", "        if record.state == R_PENDING:\n            return 0"),
    ("anyone may add approvers",
     "        if caller != ledger.owner:", "        if caller == \"\":"),
    ("approver cap off by one (6 approvers)",
     "        if count >= MAX_APPROVERS:", "        if count > MAX_APPROVERS:"),
    ("same request may be filed twice",
     "        if rid in self.requests:", "        if rid in self.requests and False:"),
    ("request id ignores whitespace normalization",
     "        rid = self._request_id(lid, requester, self._normalize_text(clean))",
     "        rid = self._request_id(lid, requester, clean)"),
    ("reserved token not checked on the purpose",
     "        if self._contains_reserved_token(clean):", "        if False:"),
    ("purpose length cap off by one",
     "        if len(clean) > MAX_PURPOSE_LENGTH:", "        if len(clean) >= MAX_PURPOSE_LENGTH:"),
    ("ledger request cap off by one",
     "        if index >= MAX_REQUESTS_PER_LEDGER:", "        if index > MAX_REQUESTS_PER_LEDGER:"),
    ("fence strip: no gap and a single pass (cross-token rebuild survives)",
     "            cleaned = cleaned[:index] + \" \" + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        # Fixed point: repeat until nothing changes, so nested fragments\n        # such as \"<<TAG>TAG>\" cannot rebuild a marker after one pass.\n        cleaned = value\n        while True:\n            before = cleaned\n            for token in RESERVED_TOKENS:\n                cleaned = self._remove_token(cleaned, token)\n            if cleaned == before:\n                return \" \".join(cleaned.split())",
     "            cleaned = cleaned[:index] + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        cleaned = value\n        for token in RESERVED_TOKENS:\n            cleaned = self._remove_token(cleaned, token)\n        return \" \".join(cleaned.split())"),
    ("wallet leaks into the prompt",
     "        safe_purpose = self._fence_strip(purpose)",
     "        safe_purpose = self._fence_strip(purpose) + \" \" + str(gl.message.sender_address)"),
    ("approve: caller checked before state",
     "        if record.state != R_PENDING:\n            raise gl.vm.UserError(\"This request is not pending\")\n        caller = str(gl.message.sender_address).lower()\n        if (record.ledger_id + \"|\" + caller) not in self.approvers:\n            raise gl.vm.UserError(\"Only an approver may approve\")",
     "        caller = str(gl.message.sender_address).lower()\n        if (record.ledger_id + \"|\" + caller) not in self.approvers:\n            raise gl.vm.UserError(\"Only an approver may approve\")\n        if record.state != R_PENDING:\n            raise gl.vm.UserError(\"This request is not pending\")"),
    ("today ignores the day of month",
     "        y, m, d = int(s[0:4]), int(s[5:7]), int(s[8:10])", "        y, m, d = int(s[0:4]), int(s[5:7]), 1"),
]
